# docker-compose.deploy.yml - For deploying from Docker Hub images
version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: box-management-mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=box_management
    networks:
      - internal
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: YOUR-DOCKERHUB-USERNAME/box-management-backend:latest
    container_name: box-management-backend
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=box_management
      - CORS_ORIGINS=
    networks:
      - internal

  nginx:
    image: nginx:alpine
    container_name: box-management-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-dynamic.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - internal

  frontend:
    image: YOUR-DOCKERHUB-USERNAME/box-management-frontend:latest
    container_name: box-management-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=
    networks:
      - internal

volumes:
  mongodb_data:

networks:
  internal:
    driver: bridge