# docker-compose.sqlite.yml - Development with SQLite
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: box-management-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/box_management.db
    volumes:
      - ./backend:/app
      - ./data:/app/data
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: box-management-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true

volumes:
  data:

networks:
  default:
    name: box-management-network